EclipseCCR = ["EclipseRule"]
Java = ["JavaNon"]
Matlab = ["MatlabNon"]
Navigation = ["NavigationNon"]
Prolog = ["PrologNon"]
Python = ["PythonNon"]
Rust = ["RustNon"]
VHDL = ["VHDLnon"]
VSCodeCcrRule = ["VSCodeNonCcrRule"]
