_enabled_ordered = ["GrammarActivatorRule", "HooksActivationRule", "DragonSink", "CustomNavigationGlobal", "CustomMouse", "CustomExplorer", "CustomNavigation", "CustomNotepad", "CustomProgramming", "CustomCPP", "CustomVisualStudio"]
_internal = ["GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "ManualGrammarReloadRule"]

[whitelisted]
AcrobatRule = false
Again = false
Alias = false
Alphabet = false
AtomRule = false
Bash = false
BringRule = false
CPP = false
CSS = false
CSharp = false
CasterRule = false
ChainAlias = false
ChromeRule = false
CustomCPP = true
CustomExplorer = true
CustomMouse = true
CustomNavigation = true
CustomNavigationGlobal = true
CustomNotepad = true
CustomProgramming = true
CustomPython = true
CustomVisualStudio = true
Dart = false
DouglasGridRule = false
DragonRule = false
DragonSink = true
EclipseCCR = false
EclipseRule = false
EmacsRule = false
ExcelRule = false
FileDialogueRule = false
FirefoxRule = false
FlashDevelopRule = false
FoxitRule = false
GitBashRule = false
GitHubDeskRule = false
GitterRule = false
Go = false
HMCConfirmRule = false
HMCDirectoryRule = false
HMCHistoryRule = false
HMCLaunchRule = false
HMCRule = false
HMCSettingsRule = false
HTML = false
HardwareRule = false
Haxe = false
HistoryRule = false
IERule = false
Java = false
JavaNon = false
Javascript = false
JetbrainsRule = false
JustDictation = true
KDiff3Rule = false
LaTeX = false
LegionGridRule = false
LyxRule = false
MSTeamsRule = false
MSVCRule = false
MSWordRule = false
Markdown = false
Matlab = false
MatlabNon = false
MouseAlternativesRule = false
NPPRule = false
Navigation = false
NavigationNon = false
Numbers = false
OutlookRule = false
Prolog = false
PrologNon = false
Punctuation = false
Python = false
PythonNon = false
RStudioRule = false
RainbowGridRule = false
Rlang = false
Rust = false
RustNon = false
SQL = false
SQLDeveloperRule = false
SSMSRule = false
SikuliManagementRule = false
SikuliRule = false
SpellingWindowRule = false
SublimeRule = false
SudokuGridRule = false
SyncDirsRule = false
TextManipulation = false
TotalCommanderRule = false
TyporaRule = false
UnityRule = false
VHDL = false
VHDLnon = false
VSCodeCcrRule = false
VSCodeNonCcrRule = false
VisualStudioRule = false
VoiceDevCommands = false
WebexTeamsRule = false
WindowManagementRule = false
WindowsSpeechRecognitionRule = false
falseAcrobatRule = false
fmanRule = false
